version: 2
  jobs:
    boddy:
      docker:
          - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "A first hello"
    sally:
      docker:
          - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "Double hello"
    workflows:
      version: 2
      boddy_sally:
        jobs:
          - boddy
          - sally
